graphhopper:
  datareader.file: /data/germany-latest.osm.pbf
  graph.location: /graphhopper/graph-cache

  profiles:
    - name: car
      vehicle: car
      weighting: fastest

    - name: truck
      vehicle: truck
      weighting: fastest
      turn_costs: true

  profiles_ch:
    - profile: car

  routing:
    ch.disabling_allowed: true

server:
  application_connector:
    type: http
    port: 8989
  admin_connector:
    type: http
    port: 8990
